version: '3.8'

services:
  db:
    container_name: postgres_container
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app_network

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - app_network
    depends_on:
      - db

  app:
    container_name: app_container
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: db
      DB_PORT: 5432
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - app_network
    depends_on:
      - db
    

volumes:
  postgres_data: # Volume to persist PostgreSQL data
  pgadmin_data:  # Volume to persist pgAdmin configurations

networks:
  app_network:
    driver: bridge
