FROM python:3.12-slim

RUN useradd -m appuser

WORKDIR /app

RUN pip install --upgrade pip

COPY . .
RUN pip install -r requirements.txt

RUN chown -R appuser:appuser /app
USER appuser

CMD ["flask", "run", "--host=0.0.0.0"]
